pub const RABBITMQ_MANAGEMENT_ROOT: &str = "RABBITMQ_MANAGEMENT_ROOT";
pub const RABBITMQ_MANAGEMENT_PASSWORD: &str = "RABBITMQ_MANAGEMENT_PASSWORD";
pub const RABBITMQ_MANAGEMENT_USERNAME: &str = "RABBITMQ_MANAGEMENT_USERNAME";
