pub(crate) const RABBITMQ_MANAGEMENT_ROOT: &str = "RABBITMQ_MANAGEMENT_ROOT";
pub(crate) const RABBITMQ_MANAGEMENT_PASSWORD: &str = "RABBITMQ_MANAGEMENT_PASSWORD";
pub(crate) const RABBITMQ_MANAGEMENT_USERNAME: &str =
    "RABBITMQ_MANAGERABBITMQ_MANAGEMENT_USERNAMEMENT_PASSWORD";
